import { ZDropOption } from "../../../../../components/ZDrop/types/zDropTypes";

export const survivorOptionsObjects: ZDropOption[] = [
  {
    id: 1,
    stateId: 0,
    value: "hiroshi",
    label: "Hiroshi",
    iconPath: `icons/survivors/z-hiroshi.webp`,
  },
  {
    id: 2,
    stateId: 1,
    value: "john",
    label: "John",
    iconPath: `icons/survivors/z-john.webp`,
  },
  {
    id: 3,
    stateId: 2,
    value: "mike",
    label: "Mike",
    iconPath: `icons/survivors/z-mike.webp`,
  },
  {
    id: 4,
    stateId: 3,
    value: "akiko",
    label: "Akiko",
    iconPath: `icons/survivors/z-akiko.webp`,
  },
  {
    id: 5,
    stateId: 4,
    value: "mr-x",
    label: "Mr. X",
    iconPath: `icons/survivors/z-mr-x.webp`,
  },
  {
    id: 6,
    stateId: 5,
    value: "chasey",
    label: "Chasey",
    iconPath: `icons/survivors/z-chasey.webp`,
  },
  {
    id: 7,
    stateId: 6,
    value: "cheng",
    label: "Cheng",
    iconPath: `icons/survivors/z-cheng.webp`,
  },
  {
    id: 8,
    stateId: 7,
    value: "daniel",
    label: "Daniel",
    iconPath: `icons/survivors/z-daniel.webp`,
  },
  {
    id: 9,
    stateId: 8,
    value: "harper",
    label: "Harper",
    iconPath: `icons/survivors/z-harper.webp`,
  },
  {
    id: 10,
    stateId: 9,
    value: "lily",
    label: "Lily",
    iconPath: `icons/survivors/z-lily.webp`,
  },
  {
    id: 11,
    stateId: 10,
    value: "do-yun",
    label: "Do Yun",
    iconPath: `icons/survivors/z-do-yun.webp`,
  },
  {
    id: 12,
    stateId: 11,
    value: "lisa",
    label: "Lisa",
    iconPath: `icons/survivors/z-lisa.webp`,
  },
  {
    id: 13,
    stateId: 12,
    value: "misaki",
    label: "Misaki",
    iconPath: `icons/survivors/z-misaki.webp`,
  },
  {
    id: 14,
    stateId: 13,
    value: "orphans",
    label: "Orphans",
    iconPath: `icons/survivors/z-orphans.webp`,
  },
  {
    id: 15,
    stateId: 14,
    value: "robert",
    label: "Robert",
    iconPath: `icons/survivors/z-robert.webp`,
  },
  {
    id: 16,
    stateId: 15,
    value: "karl",
    label: "Karl",
    iconPath: `icons/survivors/z-karl.webp`,
  },
  {
    id: 17,
    stateId: 16,
    value: "hiroto",
    label: "Hiroto",
    iconPath: `icons/survivors/z-hiroto.webp`,
  },
  {
    id: 18,
    stateId: 17,
    value: "sarah",
    label: "Sarah",
    iconPath: `icons/survivors/z-sarah.webp`,
  },
  {
    id: 19,
    stateId: 18,
    value: "ren",
    label: "Ren",
    iconPath: `icons/survivors/z-ren.webp`,
  },
  {
    id: 20,
    stateId: 19,
    value: "thomas",
    label: "Thomas",
    iconPath: `icons/survivors/z-thomas.webp`,
  },
  {
    id: 21,
    stateId: 20,
    value: "william",
    label: "William",
    iconPath: `icons/survivors/z-william.webp`,
  },
];

export const weaponOptionsObjects: ZDropOption[] = [
  {
    id: 1,
    stateId: 0,
    label: "Fists",
    value: "fists",
    iconPath: `icons/weapons/z-fists.webp`,
  },
  {
    id: 2,
    stateId: 1,
    label: "Knives",
    value: "knives",
    iconPath: `icons/weapons/z-knives.webp`,
  },
  {
    id: 3,
    stateId: 2,
    label: "Hammers",
    value: "hammers",
    iconPath: `icons/weapons/z-hammers.webp`,
  },
  {
    id: 4,
    stateId: 3,
    label: "Shovels",
    value: "shovels",
    iconPath: `icons/weapons/z-shovels.webp`,
  },
  {
    id: 5,
    stateId: 4,
    label: "Axes",
    value: "axes",
    iconPath: `icons/weapons/z-axes.webp`,
  },
  {
    id: 6,
    stateId: 5,
    label: "Swords",
    value: "swords",
    iconPath: `icons/weapons/z-swords.webp`,
  },
  {
    id: 7,
    stateId: 6,
    label: "Chainsaws",
    value: "chainsaws",
    iconPath: `icons/weapons/z-chainsaws.webp`,
  },
  {
    id: 8,
    stateId: 7,
    label: "Bows",
    value: "bows",
    iconPath: `icons/weapons/z-bows.webp`,
  },
  {
    id: 9,
    stateId: 8,
    label: "Eagles",
    value: "eagles",
    iconPath: `icons/weapons/z-eagles.webp`,
  },
  {
    id: 10,
    stateId: 9,
    label: "Uzis",
    value: "uzis",
    iconPath: `icons/weapons/z-uzis.webp`,
  },
  {
    id: 11,
    stateId: 10,
    label: "AK-47s",
    value: "AK-47s",
    iconPath: `icons/weapons/z-AK-47s.webp`,
  },
  {
    id: 12,
    stateId: 11,
    label: "M4s",
    value: "M4s",
    iconPath: `icons/weapons/z-M4s.webp`,
  },
  {
    id: 13,
    stateId: 12,
    label: "Shotguns",
    value: "shotguns",
    iconPath: `icons/weapons/z-shotguns.webp`,
  },
  {
    id: 14,
    stateId: 13,
    label: "Snipers",
    value: "snipers",
    iconPath: `icons/weapons/z-snipers.webp`,
  },
  {
    id: 15,
    stateId: 14,
    label: "Armored Motorbike",
    value: "armored-motorbike",
    iconPath: `icons/weapons/z-armored-motorbike.webp`,
  },
  {
    id: 16,
    stateId: 15,
    label: "Armored Police Car",
    value: "armored-police-car",
    iconPath: `icons/weapons/z-armored-police-car.webp`,
  },
  {
    id: 17,
    stateId: 16,
    label: "Armored Car",
    value: "armored-car",
    iconPath: `icons/weapons/z-armored-car.webp`,
  },
  {
    id: 18,
    stateId: 17,
    label: "Armored Truck",
    value: "armored-truck",
    iconPath: `icons/weapons/z-armored-truck.webp`,
  },
  {
    id: 19,
    stateId: 18,
    label: "Tank",
    value: "tank",
    iconPath: `icons/weapons/z-tank.webp`,
  },
  {
    id: 20,
    stateId: 19,
    label: "Gunship",
    value: "gunship",
    iconPath: `icons/weapons/z-gunship.webp`,
  },
  {
    id: 21,
    stateId: 20,
    label: "Jet Fighter",
    value: "jet-fighter",
    iconPath: `icons/weapons/z-jet-fighter.webp`,
  },
  {
    id: 22,
    stateId: 21,
    label: "Nuke",
    value: "nuke",
    iconPath: `icons/weapons/z-nuke.webp`,
  },
];

export const zombieOptionsObjects: ZDropOption[] = [
  {
    id: 1,
    stateId: 0,
    label: "Zombie 0",
    value: "z-0",
    locations: ["city center", "suburban area", "downtown alley"],
    iconPath: `icons/zombies/z-${0}.webp`,
  },
  {
    id: 2,
    stateId: 1,
    label: "Zombie 1",
    value: "z-1",
    locations: ["abandoned mall", "city library", "city high school"],
    iconPath: `icons/zombies/z-${1}.webp`,
  },
  {
    id: 3,
    stateId: 2,
    label: "Zombie 2",
    value: "z-2",
    locations: ["suburban area", "industrial park", "sports stadium"],
    iconPath: `icons/zombies/z-${2}.webp`,
  },
  {
    id: 4,
    stateId: 3,
    label: "Zombie 3",
    value: "z-3",
    locations: ["city center", "business district", "downtown alley"],
    iconPath: `icons/zombies/z-${3}.webp`,
  },
  {
    id: 5,
    stateId: 4,
    label: "Zombie 4",
    value: "z-4",
    locations: [
      "city park",
      "industrial park",
      "business district",
      "downtown alley",
      "sports stadium",
    ],
    iconPath: `icons/zombies/z-${4}.webp`,
  },
  {
    id: 6,
    stateId: 5,
    label: "Zombie 5",
    value: "z-5",
    locations: ["city high school", "abandoned mall"],
    iconPath: `icons/zombies/z-${5}.webp`,
  },
  {
    id: 7,
    stateId: 6,
    label: "Zombie 6",
    value: "z-6",
    locations: ["military campus", "military base", "suburban area"],
    iconPath: `icons/zombies/z-${6}.webp`,
  },
  {
    id: 8,
    stateId: 7,
    label: "Zombie 7",
    value: "z-7",
    locations: ["abandoned mall", "city center", "suburban area"],
    iconPath: `icons/zombies/z-${7}.webp`,
  },
  {
    id: 9,
    stateId: 8,
    label: "Zombie 8",
    value: "z-8",
    locations: ["city hospital"],
    iconPath: `icons/zombies/z-${8}.webp`,
  },
  {
    id: 10,
    stateId: 9,
    label: "Zombie 9",
    value: "z-9",
    locations: ["military campus", "military base"],
    iconPath: `icons/zombies/z-${9}.webp`,
  },
  {
    id: 11,
    stateId: 10,
    label: "Zombie 10",
    value: "z-10",
    locations: ["entertainment district", "city park"],
    iconPath: `icons/zombies/z-${10}.webp`,
  },
  {
    id: 12,
    stateId: 11,
    label: "Zombie 11",
    value: "z-11",
    locations: [
      "suburban area",
      "city kindergarten",
      "city park",
      "abandoned mall",
    ],
    iconPath: `icons/zombies/z-${11}.webp`,
  },
  {
    id: 13,
    stateId: 12,
    label: "Zombie 12",
    value: "z-12",
    locations: ["industrial park", "sports stadium", "suburban area"],
    iconPath: `icons/zombies/z-${12}.webp`,
  },
  {
    id: 14,
    stateId: 13,
    label: "Zombie 13",
    value: "z-13",
    locations: ["mysterious forests", "abandoned village"],
    iconPath: `icons/zombies/z-${13}.webp`,
  },
  {
    id: 15,
    stateId: 14,
    label: "Zombie 14",
    value: "z-14",
    locations: ["abandoned mall", "gas station"],
    iconPath: `icons/zombies/z-${14}.webp`,
  },
  {
    id: 16,
    stateId: 15,
    label: "Zombie 15",
    value: "z-15",
    locations: ["suburban area", "downtown alley", "abandoned mall"],
    iconPath: `icons/zombies/z-${15}.webp`,
  },
  {
    id: 17,
    stateId: 16,
    label: "Zombie 16",
    value: "z-16",
    locations: [
      "suburban area",
      "city kindergarten",
      "city park",
      "abandoned mall",
    ],
    iconPath: `icons/zombies/z-${16}.webp`,
  },
];
